spring:
  main:
    banner-mode: off
  thymeleaf:
    cache: false
  jpa:
    defer-datasource-initialization: true
    open-in-view: false # 트랜잭션 범위 밖에서 영속성 컨텍스트를 유지할지 여부
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
#  datasource:
#    url: ${db.url}
#    username: ${db.username}
#    password: ${db.password}
#    driver-class-name: ${db.driver-class-name}
    hikari:
      connection-timeout: 30000  # 커넥션 타임아웃 설정 (ms)
      maximum-pool-size: 10  # 커넥션 풀의 최대 크기 설정
      minimum-idle: 5  # 유휴 커넥션을 유지할 최소한의 커넥션 수 설정
      idle-timeout: 600000  # 유휴 커넥션의 최대 유지 시간 설정 (ms)
      pool-name: MyHikariCP  # 커넥션 풀의 이름 설정
      validation-timeout: 5000  # 커넥션 유효성 검사 타임아웃 설정 (ms)
      auto-commit: true  # 자동 커밋 모드 설정
server:
  port: 7070
  servlet:
    session:
      timeout: 600  # 600초 10분임, 기본값 30분
db:
  url: jdbc:mysql://localhost:3306/blog_b202012070
  username: root
  password: cometrue
  driver-class-name: com.mysql.cj.jdbc.Driver
